version: "3.0"
services:
  app:
    build: .
    ports:
      - 8080:8080

    volumes:
      - .:/usr/app
      - /usr/app/node_modules

    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
